import React from 'react'


export const metadata = {
    title: 'Welcomr Careers Page',
    description: 'Generated by create next app',
  }



const  CareersLayout = ({
    children, 
}) => {
  return (
    <section>
        {children}
    </section>
  )
}

export default CareersLayout