


export const metadata = {
  title: 'Welcome About Page',
  description: 'Generated by create next app',
}


export default function AboutLayout({
    children, // will be a page or nested layout
  }) {
    return (
      <section>
        {/* Include shared UI here e.g. a header or sidebar */}
        <nav></nav>
   
        {children}
      </section>
    )
  }