import NavigationBar from '@/components/NavigationBar'
import './globals.css'
import { Inter } from 'next/font/google'
import { FooterPage } from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Welcomr Home Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <NavigationBar />

        {children}
        <FooterPage />
      </body>
    </html>
  )
}
